version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - DB_SOURCE=jdbc:postgresql://db:5432/auditorias
      - DB_USERNAME=trejito
      - DB_PASSWORD=1234
      - API_KEY=7ca0086417fee50057b06f637758b88c
      - GEONAMES_USERNAME=trejito
      - DB_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: auditorias
      POSTGRES_USER: trejito
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
